# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: 'about/'
    weight: 10
  - name: Team
    url: 'docs/team/'
    identifier: team
    weight: 20
  - name: Papers
    url: 'docs/publications'
    weight: 30
  - name: Workflows
    url: 'docs/project'
    weight: 40
  - name: Media
    url: 'docs/multimedia'
    weight: 70
  - name: Guides
    url: 'docs/fieldguides'
    weight: 50
  - name: Workshops
    url: 'docs/workshops'
    weight: 60
main_right:
  - name: ' '
    identifier: portal
    pre: <i class="fa-solid fa-door-closed"></i>
    url: '#portal'
    weight: 30
  - name: ' '
    identifier: github
    pre: <i class="fab fa-github fa-lg"></i>
    url: 'https://github.com/istmobiome/istmobiome-web'
    weight: 280

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
